name: Publish Package

on:
  push:
    tags:
      - "nest-teleforge-v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lib:build

      - run: |
          cd libs/nest-teleforge
          npm publish
